flightapi:
  hostname: 'node.locomote.com'
  port: 80
  base_path: '/code-task'

logger:
  level: silly

webserver:
  host: '127.0.0.1'
  port: 3000
  handler:
    flights:
      add_days: 2
      subtract_days: 2